### ISSUE TITLE
docker dependency

### ISSUE THREAD

**Issue by alexisargyris** [softprops/serverless-aws-rust#5]
Hello,

I am trying to get the most basic example working on a windows machine. While attempting to deploy, I get `Dockerized Rust build encountered an error: Error: spawnSync docker ENOENT null`. I googled a bit and found [this ](https://github.com/serverless/serverless/issues/5663#issuecomment-452444370)which may be relevant but I'm not sure how I should proceed. Any suggestions?

Thanks in advance

**Comment by softprops** [comment]
In order to provide the build rust in an environment that most closely represents the lambda runtime your function will be running on we build functions in a docker container that replicates that environment. Testing this support in windows for me has been a hurdle I haven't been able to get over yet because I don't have windows familiarity way emulation a test. Input on that would be great because I'd definitely love to support windows as well.

**Comment by alexisargyris** [comment]
It seems that Windows is not a realistic option yet. Switched to WSL (Windows Subsystem for Linux). I was able to build and deploy to AWS Lambda but the function crashes. The issue is documented [here](https://github.com/awslabs/aws-lambda-rust-runtime/issues/17).

**Comment by softprops** [comment]
update on this. It's now possible to opt out of docker with a serverless rust `dockerless: true` setting.

See https://github.com/softprops/serverless-rust#-experimental-local-builds for more details
